"""Regenerate `docs/AML_RULE_CATALOG.md` from the code it documents.

A catalogue maintained by hand drifts from the rules the moment a threshold
changes, and a drifted catalogue is worse than none: a reviewer argues with a
rule that no longer exists. So the document is generated, and
`tests/test_docs.py` fails if it stops matching the code.

    python scripts/generate_catalogue.py
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from corridoros.risk.aggregate import (  # noqa: E402
    CASE_STATES,
    CASE_WINDOW,
    DEDUP_WINDOW,
    FORBIDDEN_STATES,
)
from corridoros.risk.priority import (  # noqa: E402
    BANDS,
    FACTOR_LABELS,
    PRIORITY_VERSION,
    WEIGHTS,
)
from corridoros.risk.rules import FAMILIES, RULES, RULES_VERSION  # noqa: E402
from corridoros.risk.typologies import TYPOLOGIES, TYPOLOGY_VERSION  # noqa: E402

FACTOR_DETAIL = {
    "signal_strength": "the severity of the strongest typology on the subject",
    "corroboration": "independent typologies agreeing — a single typology pays nothing",
    "amount": "value at stake, on a log scale between 5,000 and 500,000 USD",
    "velocity": "transfers per day across the case window",
    "network_breadth": "counterparties and countries involved",
    "information_gaps": "whether beneficiary information or purpose is absent",
    "entity_history": "the entity's own risk rating and KYB state",
    "waiting_time": "queue fairness — age must eventually win",
}


def render() -> str:
    lines: list[str] = []
    w = lines.append

    w("# Rule and typology catalogue")
    w("")
    w("<!-- Generated by scripts/generate_catalogue.py — do not edit by hand. -->")
    w("")
    w("Two deterministic layers. **No model participates in either** — not in detection, not in")
    w("severity, not in prioritisation. Every alert on this page is reproducible from the data alone.")
    w("")
    w(
        f"Rules version `{RULES_VERSION}` · typology version `{TYPOLOGY_VERSION}` · "
        f"priority version `{PRIORITY_VERSION}`"
    )
    w("")
    w("## Layer 1 — twenty-one rules over one payment")
    w("")
    w("Adapted from CrossBorder RiskOps' twenty acquiring rules. Eleven carry over with the subject")
    w("changed; the rest replace card-specific rules (authorisation gaps, chargebacks, merchant")
    w("category codes, device fingerprints) with the corridor equivalents. A rule whose inputs the")
    w("context does not carry returns nothing rather than guessing.")
    w("")
    w("`signal_id` is the vocabulary the FinSafe intervention ladder was measured against. A rule")
    w("with no equivalent there contributes to the risk band and the AML queue without silently")
    w("moving an intervention level that evaluation never covered.")
    w("")
    for family in FAMILIES:
        members = [spec for spec in RULES.values() if spec.family == family]
        w(f"### {family.replace('_', ' ').title()}")
        w("")
        w("| Rule | Severity | Fires when | Reads | Signal |")
        w("| --- | --- | --- | --- | --- |")
        for spec in members:
            reads = ", ".join(f"`{item}`" for item in spec.reads)
            signal = f"`{spec.signal_id}`" if spec.signal_id else "—"
            w(
                f"| **{spec.rule_id}**<br>{spec.title} | {spec.severity} | "
                f"{spec.reason} | {reads} | {signal} |"
            )
        w("")

    w("## Layer 2 — six AML typologies over the monitored feed")
    w("")
    w("Ported from RiskOps with thresholds and severities intact. A typology is a **shape of")
    w("behaviour, not a verdict**: an unusual transaction is not a laundered transaction, and")
    w("nothing in this system can conclude otherwise.")
    w("")
    for typology in TYPOLOGIES:
        w(f"### {typology.typology_id} — {typology.title}")
        w("")
        w(f"*{typology.question}*")
        w("")
        thresholds = ", ".join(f"`{k}={v:g}`" for k, v in typology.thresholds.items())
        w(f"**Severity** {typology.severity} · **Thresholds** {thresholds}")
        w("")
        w("**What would argue against it**")
        w("")
        for hint in typology.counter_evidence_hints:
            w(f"- {hint}")
        w("")

    w("## Priority: which case a person opens next, and why")
    w("")
    w("An ordering, not a verdict. Every factor's contribution is computed separately and rendered")
    w("as a breakdown, because an investigator who disagrees with the ordering has to see which")
    w("factor produced it.")
    w("")
    w("| Factor | Weight | What it measures |")
    w("| --- | --- | --- |")
    for factor, weight in WEIGHTS.items():
        w(f"| {FACTOR_LABELS[factor]} | {weight} | {FACTOR_DETAIL[factor]} |")
    w("")
    w(
        "Weights sum to 1.0, asserted at import. Bands: "
        + ", ".join(f"`{name}` ≥ {cut}" for cut, name in BANDS)
        + "."
    )
    w("")
    w("## Alerts are not cases")
    w("")
    w(
        f"Two alerts of the same typology on the same subject within **{DEDUP_WINDOW.days} days** "
        "are the same finding observed twice; the widest observation survives and the count it "
        "absorbed is kept."
    )
    w(
        f"Alerts on one subject within **{CASE_WINDOW.days} days** are one case — one story about "
        "an account, not several queues to work — and the reason for each merge is written down."
    )
    w("")
    w("Case states: " + ", ".join(f"`{state}`" for state in CASE_STATES) + ".")
    w("")
    w(
        "Deliberately absent, and asserted absent in `tests/test_aml.py`: "
        + ", ".join(f"`{state}`" for state in FORBIDDEN_STATES)
        + "."
    )
    w("This system can say a pattern is present and that a person looked at it. It cannot say a")
    w("crime happened, and a state named for that conclusion would invite the claim to be made by")
    w("clicking.")
    w("")
    return "\n".join(lines)


def main() -> int:
    target = ROOT / "docs" / "AML_RULE_CATALOG.md"
    target.write_text(render(), encoding="utf-8")
    print(f"wrote {target.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
